Fix recent navigation regressions.
AdaCore/libadalang pull request #830
Opened 2021-09-23 15:21 UTC by Roldak

2021-09-23 15:30 UTC, pmderodat requested changes

2021-09-23 15:30 UTC, pmderodat commented on user_manual/changes/U923-017.yaml
> +title: Fix navigation on homonym packages.
No full stop for titles

2021-09-23 15:31 UTC, Roldak commented on user_manual/changes/U923-017.yaml
> +title: Fix navigation on homonym packages.
fixed!

2021-09-24 10:15 UTC, pmderodat reviewed
Thanks! Leaving the approval of ast.py changes to @raph-amiard

2021-09-24 10:15 UTC, pmderodat approved these changes

2021-09-24 10:24 UTC, raph-amiard approved these changes

2021-09-24 13:10 UTC, merged