Add a new property to query the kind of a CallExpr
AdaCore/libadalang pull request #926
Opened 2022-01-20 09:58 UTC by thvnx

Add a new property `CallExpr.kind` to query the kind of a `CallExpr`
(call, array slice, array index, or type conversion). It returns a
`CallExprKind` enum value.

TN: UC22-030

2022-01-31 10:53 UTC, Roldak requested changes
More general comment: It is said in the original ticket that this work could allow removing some duplicated logic. Could you find any opportunities to do so?

2022-01-31 10:53 UTC, Roldak commented on ada/ast.py
> +    NoCallExpr = EnumValue(is_default=True)
Is it necessary to have the `NoCallExpr` value? Maybe we should raise an exception instead?

2022-01-31 10:53 UTC, Roldak commented on testsuite/tests/properties/call_expr_kind/kind.adb
> +   --% node.f_expr.p_is_constant
Not sure this belongs here! :smile:

2022-01-31 16:07 UTC, thvnx commented
> More general comment: It is said in the original ticket that this work could allow removing some duplicated logic. Could you find any opportunities to do so?

Actually, not really. I just simplified `Name.is_constant` property but I didn't find any other place where it would be beneficial to call `Name.kind`. I could move the code for `is_call`, or `is_array_slice` here and call `kind` where they are used, not sure it worth the effort though.

2022-02-02 14:07 UTC, Roldak commented
> I could move the code for is_call, or is_array_slice here and call kind where they are used, not sure it worth the effort though.

I don't think it's a good idea either. Let's leave it like that then, thanks for investigating!

2022-02-02 14:07 UTC, Roldak submitted a review, later dismissed

2022-02-02 16:45 UTC, Roldak approved these changes

2022-02-02 17:18 UTC, merged